### ISSUE TITLE
Pls fix these two Warnings!

### ISSUE THREAD

**Issue by iosoft** [joaofl/hassio-addons#10]
I get this annoying warnings in the Log system.
Pls fix it.

> 21-05-30 08:09:02 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Hassio Hostapd Extended

> 21-05-30 08:09:05 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Hassio Hostapd Extended

**Comment by joaofl** [comment]
So you think I should work on it because it is annoying for you?

**Comment by joaofl** [comment]
FYI, access level utilized is required to be able to access the Eth dongle + networking configurations.

**Comment by iosoft** [comment]
> So you think I should work on it because it is annoying for you?

removing warnings is part of code optimization.

**Comment by joaofl** [comment]
A new release reduced the requirements levels, and should solve this problem. Closing for now. Might reopen if observed again.
