### ISSUE TITLE
Supported devices 

### ISSUE THREAD

**Issue by liroman2312** [joaofl/hassio-addons#16]
Hi the addon works great I just wana know which external usb wifi doungel is supported by your addon

**Comment by joaofl** [comment]
Hi @liroman2312 
I don't have an exact list of the devices, but its basically the dongles with Atheros chipsets, whose drivers are distributed by the following packages (beside the native ones):
-     linux-firmware-other
-     linux-firmware-ath6k
-     linux-firmware-ath10k
-     linux-firmware-ath9k_htc

You can check which chipsets are supported by each of the packages above from the Alpine Linux repos (https://pkgs.alpinelinux.org/packages?name=linux-firmware*&branch=edge)

If you are missing a given driver, feel free to point out which package that may contain the drivers you need, and we can potentially add them to the add-on.

**Comment by liroman2312** [comment]
![Screenshot_20220429-075937_AliExpress](https://user-images.githubusercontent.com/101349420/165887491-495b8ec9-0e67-49c5-a78a-e8aeec9b436b.jpg)

For now o ordered this usb I saw you are working with thise one so this one will work just play and play correct?

**Comment by joaofl** [comment]
Looks exactly like the one I use. Should work fine!

So I will close this ticket for now. Feel free to re-open it if you have further question.
