### ISSUE TITLE
Hassio 2022.5

### ISSUE THREAD

**Issue by lele89m** [joaofl/hassio-addons#19]
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by joaofl** [comment]
Thanks for reporting. The issue was fixed. Please check for the latest release.

**Comment by simongoudie** [comment]
I'm getting the S6-overlay same error when starting telegraf2hassio (v0.1.0) - would it be possible to also update the 'init: false' setting in that add-on's configuration? Thanks for your work, @joaofl.
