### ISSUE TITLE
telegraf2hassio - 'could not get host informations'

### ISSUE THREAD

**Issue by mauriceatkinson** [joaofl/hassio-addons#23]
I have installed telegraf2hassio and the log file reports it has connected to the mqtt broker.

I have added the [[output.mqtt]] as per your telegraf.conf install but I get the error in the telegraf log file
`2022-12-14T23:10:47Z E! [agent] Failed to connect to [outputs.mqtt], retrying in 15s, error was 'could not get host informations'`

What am I doing wrong?

**Comment by joaofl** [comment]
This seems like a miss-configuration of telegraf itself, making it unable to reach your MQTT broker.

Have you checked the full example config, and if you are not missing any other field related to the host definition?

Check it here: https://github.com/joaofl/hassio-addons/blob/master/telegraf2hassio/resources/telegraf.conf

**Comment by mauriceatkinson** [comment]
Sorry.  I omitted to add the server details into the output.mqtt section.  Once configured this works great.  thanks

**Comment by joaofl** [comment]
> Sorry. I omitted to add the server details into the output.mqtt section. Once configured this works great. thanks

It is also missing on the template config I think. I should fix that!
