### ISSUE TITLE
telegraf2hassio can not be installed

### ISSUE THREAD

**Issue by LazyLizardJago** [joaofl/hassio-addons#26]
I was able to add the store as documented and when the installation is started I get the following error:
The command '/bin/ash -o pipefail -c pip3 install paho-mqtt' returned a non-zero code: 1

In some community message it was reported that replacing the pip call with the apk might help. (RUN apk add py3-paho-mqtt)

core version: 2024.1.5
homeassistant OS on Raspi

**Comment by joaofl** [comment]
Thanks for reporting the bug and the solution. Just implemented it and made a new release that seems to solve the problem.

**Comment by LazyLizardJago** [comment]
Thanks for the fast fix! Works for me!
