### ISSUE TITLE
No IP Address

### ISSUE THREAD

**Issue by sh4rkt3ch** [joaofl/hassio-addons#3]
Hi, running on HASSIO using wlan0 but no device gets an IP address. Log attached:

`IEEE 802.1X: Ignore STA - 802.1X not enabled or forced for WPS
wlan0: STA 52:fa:fb:c0:0d:2a WPA: start authentication
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state INITIALIZE
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=0x20dd658 key_idx=0 set_tx=1 seq_len=0 key_len=0
   addr=52:fa:fb:c0:0d:2a
nl80211: set_key failed; err=-22 Invalid argument)
RSN: PTK removal from the driver failed
nl80211: Set STA flags - ifname=wlan0 addr=52:fa:fb:c0:0d:2a total_flags=0x60 flags_or=0x0 flags_and=0xfffffffe authorized=0
wlan0: STA 52:fa:fb:c0:0d:2a IEEE 802.1X: unauthorizing port
WPA: 52:fa:fb:c0:0d:2a WPA_PTK_GROUP entering state IDLE
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state AUTHENTICATION
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state AUTHENTICATION2
WPA: Assign ANonce - hexdump(len=32): b3 b7 3d d1 d2 1e e9 e6 e1 ab 5c 55 87 f7 95 37 6f 72 e4 56 04 b8 db 52 1b 9b 1c dc 79 2d 6a eb
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state INITPSK
Searching a PSK for 52:fa:fb:c0:0d:2a prev_psk=0
Searching a PSK for 52:fa:fb:c0:0d:2a prev_psk=0
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state PTKSTART
wlan0: STA 52:fa:fb:c0:0d:2a WPA: sending 1/4 msg of 4-Way Handshake
WPA: Send EAPOL(version=2 secure=0 mic=0 ack=1 install=0 pairwise=1 kde_len=0 keyidx=0 encr=0)
WPA: Replay Counter - hexdump(len=8): 00 00 00 00 00 00 00 01
WPA: Use EAPOL-Key timeout of 1000 ms (retry counter 1)
wlan0: hostapd_new_assoc_sta: reschedule ap_handle_timer timeout for 52:fa:fb:c0:0d:2a (300 seconds - ap_max_inactivity)
wlan0: Event EAPOL_RX (23) received
IEEE 802.1X: 121 bytes from 52:fa:fb:c0:0d:2a
   IEEE 802.1X: version=1 type=3 length=117
WPA: Received EAPOL-Key from 52:fa:fb:c0:0d:2a key_info=0x10a type=2 mic_len=16 key_data_length=22
WPA: Received Key Nonce - hexdump(len=32): e9 64 dc 30 cf 80 43 e9 ac 9a 31 83 7c 30 35 b0 0e fc 84 6f 27 1e e4 82 10 d8 31 a3 8c 6e 3f 69
WPA: Received Replay Counter - hexdump(len=8): 00 00 00 00 00 00 00 01
wlan0: STA 52:fa:fb:c0:0d:2a WPA: received EAPOL-Key frame (2/4 Pairwise)
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state PTKCALCNEGOTIATING
Searching a PSK for 52:fa:fb:c0:0d:2a prev_psk=0
WPA: PTK derivation using PRF(SHA1)
WPA: PTK derivation - A1=dc:a6:32:6e:33:a3 A2=52:fa:fb:c0:0d:2a
WPA: Nonce1 - hexdump(len=32): b3 b7 3d d1 d2 1e e9 e6 e1 ab 5c 55 87 f7 95 37 6f 72 e4 56 04 b8 db 52 1b 9b 1c dc 79 2d 6a eb
WPA: Nonce2 - hexdump(len=32): e9 64 dc 30 cf 80 43 e9 ac 9a 31 83 7c 30 35 b0 0e fc 84 6f 27 1e e4 82 10 d8 31 a3 8c 6e 3f 69
WPA: PMK - hexdump(len=32): [REMOVED]
WPA: PTK - hexdump(len=48): [REMOVED]
WPA: KCK - hexdump(len=16): [REMOVED]
WPA: KEK - hexdump(len=16): [REMOVED]
WPA: TK - hexdump(len=16): [REMOVED]
WPA: EAPOL-Key MIC using HMAC-SHA1
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state PTKCALCNEGOTIATING2
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state PTKINITNEGOTIATING
wlan0: STA 52:fa:fb:c0:0d:2a WPA: sending 3/4 msg of 4-Way Handshake
WPA: Send EAPOL(version=2 secure=1 mic=1 ack=1 install=1 pairwise=1 kde_len=46 keyidx=1 encr=1)
WPA: Replay Counter - hexdump(len=8): 00 00 00 00 00 00 00 02
Plaintext EAPOL-Key Key Data - hexdump(len=56): [REMOVED]
WPA: Encrypt Key Data using AES-WRAP (KEK length 16)
WPA: EAPOL-Key MIC using HMAC-SHA1
WPA: Use EAPOL-Key timeout of 1000 ms (retry counter 1)
wlan0: Event EAPOL_RX (23) received
IEEE 802.1X: 99 bytes from 52:fa:fb:c0:0d:2a
   IEEE 802.1X: version=1 type=3 length=95
WPA: Received EAPOL-Key from 52:fa:fb:c0:0d:2a key_info=0x30a type=2 mic_len=16 key_data_length=0
WPA: Received Key Nonce - hexdump(len=32): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
WPA: Received Replay Counter - hexdump(len=8): 00 00 00 00 00 00 00 02
wlan0: STA 52:fa:fb:c0:0d:2a WPA: received EAPOL-Key frame (4/4 Pairwise)
WPA: EAPOL-Key MIC using HMAC-SHA1
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state PTKINITDONE
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=3 addr=0x20dd658 key_idx=0 set_tx=1 seq_len=0 key_len=16
nl80211: KEY_DATA - hexdump(len=16): [REMOVED]
   addr=52:fa:fb:c0:0d:2a
wlan0: AP-STA-CONNECTED 52:fa:fb:c0:0d:2a
nl80211: Set STA flags - ifname=wlan0 addr=52:fa:fb:c0:0d:2a total_flags=0x61 flags_or=0x1 flags_and=0xffffffff authorized=1
wlan0: STA 52:fa:fb:c0:0d:2a IEEE 802.1X: authorizing port
wlan0: STA 52:fa:fb:c0:0d:2a RADIUS: starting accounting session 6326FA9BB3784AB2
wlan0: STA 52:fa:fb:c0:0d:2a WPA: pairwise key handshake completed (RSN)
nl80211: BSS Event 59 (NL80211_CMD_FRAME) received for wlan0
nl80211: RX frame da=dc:a6:32:6e:33:a3 sa=52:fa:fb:c0:0d:2a bssid=dc:a6:32:6e:33:a3 freq=2462 ssi_signal=0 fc=0xd0 seq_ctrl=0x0 stype=13 (WLAN_FC_STYPE_ACTION) len=28
wlan0: Event RX_MGMT (18) received
mgmt::action
RX_ACTION category 10 action 6 sa 52:fa:fb:c0:0d:2a da dc:a6:32:6e:33:a3 len 28 freq 2462
wlan0: STA 52:fa:fb:c0:0d:2a IEEE 802.11: handle_action - unknown action category 10 or invalid frame
IEEE 802.11: Return unknown Action frame back to sender
nl80211: send_mlme - da= 52:fa:fb:c0:0d:2a noack=0 freq=0 no_cck=0 offchanok=0 wait_time=0 fc=0xd0 (WLAN_FC_STYPE_ACTION) nlmode=3
nl80211: Use bss->freq=2462
nl80211: Drv Event 60 (NL80211_CMD_FRAME_TX_STATUS) received for wlan0
nl80211: Frame TX status event
wlan0: Event TX_STATUS (16) received
mgmt::action cb ok=0
nl80211: Drv Event 20 (NL80211_CMD_DEL_STATION) received for wlan0
nl80211: Delete station 52:fa:fb:c0:0d:2a
wlan0: Event DISASSOC (1) received
wlan0: STA 52:fa:fb:c0:0d:2a IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED 52:fa:fb:c0:0d:2a
wlan0: STA 52:fa:fb:c0:0d:2a WPA: event 2 notification
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=0x20dd658 key_idx=0 set_tx=1 seq_len=0 key_len=0
   addr=52:fa:fb:c0:0d:2a
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state DISCONNECTED
WPA: 52:fa:fb:c0:0d:2a WPA_PTK entering state INITIALIZE
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=0x20dd658 key_idx=0 set_tx=1 seq_len=0 key_len=0
   addr=52:fa:fb:c0:0d:2a
nl80211: set_key failed; err=-22 Invalid argument)
RSN: PTK removal from the driver failed
nl80211: Set STA flags - ifname=wlan0 addr=52:fa:fb:c0:0d:2a total_flags=0x0 flags_or=0x0 flags_and=0xfffffffe authorized=0
wlan0: STA 52:fa:fb:c0:0d:2a IEEE 802.1X: unauthorizing port
nl80211: sta_remove -> DEL_STATION wlan0 52:fa:fb:c0:0d:2a --> 0 (No error information)
hostapd_ht_operation_update current operation mode=0x0
hostapd_ht_operation_update new operation mode=0x0 changes=0
ap_free_sta: cancel ap_handle_timer for 52:fa:fb:c0:0d:2a`

**Comment by joaofl** [comment]
Have you installed the DHCP server?
That is a separate thing... I plan to integrate it in here, but haven't find the time yet.

**Comment by joaofl** [comment]
Install the addon below:
![image](https://user-images.githubusercontent.com/8092452/93233918-eef08680-f77b-11ea-805f-df15400c95b5.png)
Then have it configured to something like below:
![image](https://user-images.githubusercontent.com/8092452/93234019-10ea0900-f77c-11ea-9f4d-902980ba1e6e.png)

**Comment by joaofl** [comment]
Closing this issue since there was no response on this.

**Comment by joaofl** [comment]
@sh4rkt3ch It now includes a DHCP server, so you no longer need that extra addon.
