### ISSUE TITLE
Give temporary internet access

### ISSUE THREAD

**Issue by jdrobert** [joaofl/hassio-addons#4]
Is it possible to give devices temporary internet access?

I think this would be useful in the case where I want to update the firmware of a plug or lightbulb.

If not, I understand. I appreciate the work you've put into these projects.

**Comment by joaofl** [comment]
I agree that is a nice feature to have. But I still have not found the time to work on it, as well as on the DHCP boot issue.
Ill try to do it asap, and keep you posted here so you can give it a try when ready.

**Comment by joaofl** [comment]
@jdrobert I added this option as a setting. I still did not test it extensively, but should work. Please let me know how it goes for you.

**Comment by jdrobert** [comment]
Thank you! I’ll test it out this weekend.

**Comment by joaofl** [comment]
Ok, it seems that the internet is not being cut after one disables it. Have to look a bit further into how to do it.

**Comment by joaofl** [comment]
Pushed a new version today. Tested it many times, and seems to be working fine. Let me know if works for you as well.

**Comment by jdrobert** [comment]
This works great for my needs. Now that the DHCP server is included does that mean I no longer need the separate DHCP add-on?

**Comment by joaofl** [comment]
> Now that the DHCP server is included does that mean I no longer need the separate DHCP add-on?

Exactly, you can uninstall it, unless you use it for something else. Make sure you enable the server on the settings.
