### ISSUE TITLE
Atheros support

### ISSUE THREAD

**Issue by ShonP40** [joaofl/hassio-addons#5]
Will support for Atheros dongles like the TP-Link TL-WN821N be added in the future?

**Comment by joaofl** [comment]
It should be possible to do it. My problem now is that I do not have one of those to test. Ill try to add it as soon as I find the time.

**Comment by ShonP40** [comment]
Alright, thank you.

**Comment by ShonP40** [comment]
I found this page that contains more info about the USB dongle I have. Maybe it could help

http://en.techinfodepot.shoutwiki.com/wiki/TP-LINK_TL-WN821N_v2

**Comment by joaofl** [comment]
@ShonP40 Just added a couple of Atheros drivers. Please let me know if it solves your problem

**Comment by ShonP40** [comment]
I just reinstalled the addon and my USB dongle still isn't being detected.

**Comment by ShonP40** [comment]
If the details on the website I sent above are correct, the driver my wireless dongle needs is `linux-firmware-ath9k_htc`.

**Comment by ShonP40** [comment]
Well, I just tested it with `linux-firmware-ath9k_htc` and it didn't work as well

**Comment by ShonP40** [comment]
Correction, the needed driver is `carl9170`, but I can't find it on the Alpine Linux repository

**Comment by joaofl** [comment]
> If the details on the website I sent above are correct, the driver my wireless dongle needs is `linux-firmware-ath9k_htc`.

I just made a new release including all the atheros firmwares available in the repos. Please give it another try

**Comment by joaofl** [comment]
Can you ssh into your hassio and get some logs? 

Maybe install the drivers manually and see what shows up in the system logs after you insert the dongle? Also run ifconfig -a and see if the device shows up.

**Comment by ShonP40** [comment]
> > If the details on the website I sent above are correct, the driver my wireless dongle needs is `linux-firmware-ath9k_htc`.
> 
> I just made a new release including all the atheros firmwares available in the repos. Please give it another try

I already tried that driver (cloned and modified your repo). It didn’t work.

**Comment by ShonP40** [comment]
> Can you ssh into your hassio and get some logs?
> 
> Maybe install the drivers manually and see what shows up in the system logs after you insert the dongle? Also run ifconfig -a and see if the device shows up.

Did that once already. It detects the dongle, but then fails to load it.
(It doesn’t show up in `ifconfig`)

**Comment by joaofl** [comment]
So maybe its blacklisted.... Not sure. I would need logs and probably a similar dongle to test it

**Comment by ShonP40** [comment]
It works on normal Raspberry Pi OS though

Don't think that HAOS is blacklisting Wireless adapters

And the host logs only show that it's detected on the USB bus

**Comment by ShonP40** [comment]
Can you recommend a dongle that works with your addon?

**Comment by joaofl** [comment]
I'm personally using the one below, which has the Ralink chipset:
https://www.aliexpress.com/item/32834257814.html?spm=a2g0s.9042311.0.0.27424c4dyXG5IN

**Comment by ShonP40** [comment]
Sorry for the late response.

I’ll try to find a dongle with the same chipset as yours but with a smaller antenna (there isn’t a lot of space at the place my RPI is located in)
