### ISSUE TITLE
Driver for Ralink5370 USB missing ?

### ISSUE THREAD

**Issue by segore777** [joaofl/hassio-addons#8]
Hi,
I'm trying to use your addons with my USB wifi dongle, but it's not detected.
Where can I upload the driver ?
Thanks.

**Comment by joaofl** [comment]
Do you know if your dongle is supported by the Alpine Linux? Do you think you could figure out which package has that driver? In that case I can add that for you. I can not do much from here since I dont have this dongle.

**Comment by segore777** [comment]
Hi, I think it's rt2870.bin or mt7601u.bin

Here's my log

➜  ~ dmesg | grep firmware
[    0.000000] ARM_SMCCC_ARCH_WORKAROUND_1 missing from firmware
[    0.068197] raspberrypi-firmware soc:firmware: Attached to firmware from 2021                                                                                        -01-08 14:31, variant start
[    0.072208] raspberrypi-firmware soc:firmware: Firmware hash is 194a85abd768c                                                                                        7334bbadc3f1911c10a7d18ed14
[    2.532544] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455                                                                                        -sdio.raspberrypi,4-model-b.txt failed with error -2
[    5.718919] ieee80211 phy0: rt2x00lib_request_firmware: Info - Loading firmwa                                                                                        re file 'rt2870.bin'
[    5.718974] rt2800usb 1-1.1:1.0: Direct firmware load for rt2870.bin failed w                                                                                        ith error -2
[    5.718983] ieee80211 phy0: rt2x00lib_request_firmware: Error - Failed to req                                                                                        uest Firmware
[   47.542616] ieee80211 phy0: rt2x00lib_request_firmware: Info - Loading firmwa                                                                                        re file 'rt2870.bin'
[   47.545849] ieee80211 phy0: rt2x00lib_request_firmware: Info - Firmware detec                                                                                        ted - version: 0.36
[309765.761329] mt7601u 1-1.1:1.0: Direct firmware load for mt7601u.bin failed w                                                                                        ith error -2

Thanks.

**Comment by joaofl** [comment]
Nice, thanks for the info. Ill check on how to integrate this driver as soon as I find the time, and will let you know when to test it, since I can not test it properly without the hardware.

**Comment by segore777** [comment]
Hi, did you find some time to add my driver or could you send me a link to explain me how to do it by myself ? Thanks a lot.

**Comment by joaofl** [comment]
Hi @segore777 ,
It is nice that you are willing to try try. I'm really not finding the time to do it, neither I can test it.

What I suggest is: first, get yourself a terminal with root access to the home assistant. There is an addon that makes that easy.

Then, the easiest would be to find a package on the alpine linux package base, and install it using opkg on the terminal.
If by doing that, you get your USB dongle working, then it means that you found a package that introduces the drivers you need. After that it should be an wasy step to just introduce the installation of this package to this addon.

**Comment by joaofl** [comment]
On a quick search here, I found this page:
https://www.linickx.com/alpine-linux-raspberry-pi-and-wireless-wifi-firmware

Apparently, what we need to do is just to introduce a download step to in winch we download the firmware at startup.

**Comment by segore777** [comment]
Hi, I found the package it's : 
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20210716.tar.gz
but opkg doesn't work in my terminal, I don't know the command for the Home Assistant OS 6.1 to install the package.

And all the commands on your link doesn't work too...

I don't know what to do.

Thanks.

**Comment by joaofl** [comment]
Have you managed to get it working in the end?

**Comment by segore777** [comment]
Nope, I found an other dongle.On Mar 10, 2024, at 18:43, João Loureiro ***@***.***> wrote:﻿
Have you managed to get it working in the end?

**Comment by joaofl** [comment]
Ok. So I will close this issue for now.
